/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_runvision_idcardfacesdk_RunvisionUtil */

#ifndef _Included_com_runvision_idcardfacesdk_RunvisionUtil
#define _Included_com_runvision_idcardfacesdk_RunvisionUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_runvision_idcardfacesdk_RunvisionUtil
 * Method:    AuthorizeSN
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_runvision_idcardfacesdk_RunvisionUtil_AuthorizeSN
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_runvision_idcardfacesdk_RunvisionUtil
 * Method:    getAPPID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_runvision_idcardfacesdk_RunvisionUtil_getAPPID
  (JNIEnv *, jclass);

/*
 * Class:     com_runvision_idcardfacesdk_RunvisionUtil
 * Method:    getSDKKEY
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_runvision_idcardfacesdk_RunvisionUtil_getSDKKEY
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
